# Sample Data
## Dataset 1: Titanic data

In [1]:
import pandas as pd

print(pd.__version__)
titanic = pd.read_csv('./data/titanic.csv')
titanic.head()

3.0.5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Dataset 2 :vaccine

support `date` columns

In [2]:
import pandas as pd

vaccine = pd.read_csv('./data/country_vaccinations.csv')
vaccine['date'] = pd.to_datetime(vaccine['date'])
vaccine.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...

# summarytools
## Out-of-Box Summary

In [3]:
from summarytools import dfSummary

dfSummary(titanic)

## Collapsible Summary

In [4]:
from IPython.display import display

display(dfSummary(titanic, is_collapsible=True))
display(dfSummary(vaccine, is_collapsible=True))

## Tabbed Summary

In [5]:
from summarytools import tabset

tabset({
    'titanic': dfSummary(titanic).to_html(),
    'vaccine': dfSummary(vaccine).to_html()
    })

## Out-of-Box Frequency Table

In [6]:
from summarytools import freq

freq(titanic['Embarked'])

In [7]:
from IPython.display import display

display(freq(titanic, var='Pclass', is_collapsible=True))
display(freq(vaccine, var='vaccines', is_collapsible=True))

In [8]:
from summarytools import tabset

tabset({
    'titanic: embarked': freq(titanic['Embarked']).to_html(),
    'vaccine: source_name': freq(vaccine['source_name'], digits=1, report_nans=False, cumul=False, order='freq').to_html()
    })

# For very wide tables

use `num_pro` to parallel processing the columns. ( available since v0.3.0 )

In [9]:
# concatenate `titanic` dataset 100x to make it super wide.
df_wide = titanic.copy()
for i in range(100):
    df_wide = pd.concat([df_wide, titanic.rename(lambda x: f'{x}_{i:04d}', axis='columns')], axis = 1)
print(df_wide.shape)

(891, 1212)

In [10]:
from time import time

t1 = time()
res = dfSummary(df_wide)
t2 = time()
print(f'{t2 - t1: .2f} sec elapsed')

 9.55 sec elapsed

In [11]:
t1 = time()
res = dfSummary(df_wide, num_proc=6) # parallelize into 6 processes
t2 = time()
print(f'{t2 - t1: .2f} sec elapsed')

 4.49 sec elapsed

# Export to HTML

## save notebook checkpoint

In [12]:
%%javascript
Jupyter.notebook.save_checkpoint()
Jupyter.notebook.save_notebook()

## export HTML with embedded images

In [14]:
!jupyter nbconvert --to html "quick-start.ipynb"

[NbConvertApp] Converting notebook quick-start.ipynb to html
[NbConvertApp] WARNING | Alternative text is missing on 66 image(s).
[NbConvertApp] Writing 444182 bytes to quick-start.html